### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by yiboin** [suhangpro/matresnet#1]
"git clone --recurse-submodules git@github.com:suhangpro/matresnet.git
Cloning into 'matresnet'...
Permission denied (publickey).
fatal: Could not read from remote repository."

I cannot clone this repo, please give me some advice. Thx.

**Comment by suhangpro** [comment]
Check the "Authenticating with GitHub from Git" section in https://help.github.com/articles/set-up-git/
